import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-3/5 w-1/5 flex-col rounded-lg border">
          {children}
        </div>
      </body>
    </html>
  );
}
