import { Work_Sans } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import { ApolloWrapper } from '@/lib/apollo-wrapper';
import StyledComponentsRegistry from '@/lib/styled-components-registry';

import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'iamPocket',
  description: 'Generated by create next app',
};

const workSans = Work_Sans({
  weight: ['700', '500', '400'],
  subsets: ['latin'],
  display: 'swap',
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={workSans.className}>
      <body>
        <ApolloWrapper>
          <StyledComponentsRegistry>
            {children}
            {/* success, warning, error */}
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
          </StyledComponentsRegistry>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
